
ARG PYTHON_VERSION=3.8
FROM python:${PYTHON_VERSION} AS base


WORKDIR /app

COPY app.py docker-logo.png requirements.txt ./


FROM python:${PYTHON_VERSION}-slim 

WORKDIR /app


ARG MY_ARG=default
ENV MY_ENV=${MY_ARG}

COPY --from=base /app .

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

EXPOSE 8080

ENTRYPOINT ["python","app.py"]